2025-05-06 23:14:44,224 INFO    MainThread:3005 [wandb_setup.py:_flush():68] Current SDK version is 0.19.0
2025-05-06 23:14:44,225 INFO    MainThread:3005 [wandb_setup.py:_flush():68] Configure stats pid to 3005
2025-05-06 23:14:44,225 INFO    MainThread:3005 [wandb_setup.py:_flush():68] Loading settings from /home/joaopaulo/.config/wandb/settings
2025-05-06 23:14:44,225 INFO    MainThread:3005 [wandb_setup.py:_flush():68] Loading settings from /home/joaopaulo/Projects/internvl3-siamese/notebooks/wandb/settings
2025-05-06 23:14:44,226 INFO    MainThread:3005 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-05-06 23:14:44,226 INFO    MainThread:3005 [wandb_init.py:_log_setup():528] Logging user logs to /home/joaopaulo/Projects/internvl3-siamese/notebooks/wandb/run-20250506_231444-az0t2fy9/logs/debug.log
2025-05-06 23:14:44,226 INFO    MainThread:3005 [wandb_init.py:_log_setup():529] Logging internal logs to /home/joaopaulo/Projects/internvl3-siamese/notebooks/wandb/run-20250506_231444-az0t2fy9/logs/debug-internal.log
2025-05-06 23:14:44,227 INFO    MainThread:3005 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7bfb743d3750>
2025-05-06 23:14:44,227 INFO    MainThread:3005 [wandb_init.py:init():639] calling init triggers
2025-05-06 23:14:44,228 INFO    MainThread:3005 [wandb_init.py:init():645] wandb.init called with sweep_config: {}
config: {}
2025-05-06 23:14:44,228 INFO    MainThread:3005 [wandb_init.py:init():688] starting backend
2025-05-06 23:14:44,228 INFO    MainThread:3005 [wandb_init.py:init():692] sending inform_init request
2025-05-06 23:14:44,230 INFO    MainThread:3005 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-06 23:14:44,231 INFO    MainThread:3005 [wandb_init.py:init():705] backend started and connected
2025-05-06 23:14:44,240 INFO    MainThread:3005 [wandb_run.py:_label_probe_notebook():1327] probe notebook
2025-05-06 23:14:44,259 INFO    MainThread:3005 [wandb_init.py:init():798] updated telemetry
2025-05-06 23:14:44,260 INFO    MainThread:3005 [wandb_init.py:init():830] communicating run to backend with 90.0 second timeout
2025-05-06 23:14:44,849 INFO    MainThread:3005 [wandb_init.py:init():882] starting run threads in backend
2025-05-06 23:14:44,998 INFO    MainThread:3005 [wandb_run.py:_console_start():2443] atexit reg
2025-05-06 23:14:44,999 INFO    MainThread:3005 [wandb_run.py:_redirect():2293] redirect: wrap_raw
2025-05-06 23:14:44,999 INFO    MainThread:3005 [wandb_run.py:_redirect():2358] Wrapping output streams.
2025-05-06 23:14:45,000 INFO    MainThread:3005 [wandb_run.py:_redirect():2383] Redirects installed.
2025-05-06 23:14:45,000 INFO    MainThread:3005 [wandb_init.py:init():925] run started, returning control to user process
2025-05-06 23:14:45,247 INFO    MainThread:3005 [wandb_run.py:_config_callback():1375] config_cb None None {'output_dir': './results', 'overwrite_output_dir': False, 'do_train': False, 'do_eval': True, 'do_predict': False, 'eval_strategy': 'epoch', 'prediction_loss_only': False, 'per_device_train_batch_size': 10, 'per_device_eval_batch_size': 8, 'per_gpu_train_batch_size': None, 'per_gpu_eval_batch_size': None, 'gradient_accumulation_steps': 1, 'eval_accumulation_steps': None, 'eval_delay': 0, 'torch_empty_cache_steps': None, 'learning_rate': 5e-05, 'weight_decay': 0.0, 'adam_beta1': 0.9, 'adam_beta2': 0.999, 'adam_epsilon': 1e-08, 'max_grad_norm': 1.0, 'num_train_epochs': 20, 'max_steps': -1, 'lr_scheduler_type': 'linear', 'lr_scheduler_kwargs': {}, 'warmup_ratio': 0.0, 'warmup_steps': 0, 'log_level': 'passive', 'log_level_replica': 'warning', 'log_on_each_node': True, 'logging_dir': './logs', 'logging_strategy': 'epoch', 'logging_first_step': False, 'logging_steps': 500, 'logging_nan_inf_filter': True, 'save_strategy': 'no', 'save_steps': 500, 'save_total_limit': None, 'save_safetensors': True, 'save_on_each_node': False, 'save_only_model': False, 'restore_callback_states_from_checkpoint': False, 'no_cuda': False, 'use_cpu': False, 'use_mps_device': False, 'seed': 42, 'data_seed': None, 'jit_mode_eval': False, 'use_ipex': False, 'bf16': False, 'fp16': False, 'fp16_opt_level': 'O1', 'half_precision_backend': 'auto', 'bf16_full_eval': False, 'fp16_full_eval': False, 'tf32': None, 'local_rank': 0, 'ddp_backend': None, 'tpu_num_cores': None, 'tpu_metrics_debug': False, 'debug': [], 'dataloader_drop_last': False, 'eval_steps': None, 'dataloader_num_workers': 0, 'dataloader_prefetch_factor': None, 'past_index': -1, 'run_name': './results', 'disable_tqdm': False, 'remove_unused_columns': True, 'label_names': None, 'load_best_model_at_end': False, 'metric_for_best_model': None, 'greater_is_better': None, 'ignore_data_skip': False, 'fsdp': [], 'fsdp_min_num_params': 0, 'fsdp_config': {'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False}, 'tp_size': 0, 'fsdp_transformer_layer_cls_to_wrap': None, 'accelerator_config': {'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None}, 'deepspeed': None, 'label_smoothing_factor': 0.0, 'optim': 'adamw_torch', 'optim_args': None, 'adafactor': False, 'group_by_length': False, 'length_column_name': 'length', 'report_to': ['wandb'], 'ddp_find_unused_parameters': None, 'ddp_bucket_cap_mb': None, 'ddp_broadcast_buffers': None, 'dataloader_pin_memory': True, 'dataloader_persistent_workers': False, 'skip_memory_metrics': True, 'use_legacy_prediction_loop': False, 'push_to_hub': False, 'resume_from_checkpoint': None, 'hub_model_id': None, 'hub_strategy': 'every_save', 'hub_token': '<HUB_TOKEN>', 'hub_private_repo': None, 'hub_always_push': False, 'gradient_checkpointing': False, 'gradient_checkpointing_kwargs': None, 'include_inputs_for_metrics': False, 'include_for_metrics': [], 'eval_do_concat_batches': True, 'fp16_backend': 'auto', 'evaluation_strategy': 'epoch', 'push_to_hub_model_id': None, 'push_to_hub_organization': None, 'push_to_hub_token': '<PUSH_TO_HUB_TOKEN>', 'mp_parameters': '', 'auto_find_batch_size': False, 'full_determinism': False, 'torchdynamo': None, 'ray_scope': 'last', 'ddp_timeout': 1800, 'torch_compile': False, 'torch_compile_backend': None, 'torch_compile_mode': None, 'dispatch_batches': None, 'split_batches': None, 'include_tokens_per_second': False, 'include_num_input_tokens_seen': False, 'neftune_noise_alpha': None, 'optim_target_modules': None, 'batch_eval_metrics': False, 'eval_on_start': False, 'use_liger_kernel': False, 'eval_use_gather_object': False, 'average_tokens_across_devices': False}
2025-05-06 23:15:05,554 WARNING MsgRouterThr:3005 [router.py:message_loop():75] message_loop has been closed
2025-05-06 23:15:05,740 INFO    MainThread:3005 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2025-05-06 23:15:05,740 INFO    MainThread:3005 [wandb_init.py:_pause_backend():439] pausing backend
2025-05-06 23:15:15,180 INFO    MainThread:3005 [wandb_init.py:_resume_backend():444] resuming backend
2025-05-06 23:15:15,417 INFO    MainThread:3005 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2025-05-06 23:15:15,419 INFO    MainThread:3005 [wandb_init.py:_pause_backend():439] pausing backend
2025-05-06 23:15:17,657 INFO    MainThread:3005 [wandb_init.py:_resume_backend():444] resuming backend
2025-05-06 23:15:17,771 INFO    MainThread:3005 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2025-05-06 23:15:17,771 INFO    MainThread:3005 [wandb_init.py:_pause_backend():439] pausing backend
2025-05-06 23:15:18,067 INFO    MainThread:3005 [wandb_init.py:_resume_backend():444] resuming backend
2025-05-06 23:15:18,166 INFO    MainThread:3005 [wandb_setup.py:_flush():68] Current SDK version is 0.19.0
2025-05-06 23:15:18,167 INFO    MainThread:3005 [wandb_setup.py:_flush():68] Configure stats pid to 3005
2025-05-06 23:15:18,167 INFO    MainThread:3005 [wandb_setup.py:_flush():68] Loading settings from /home/joaopaulo/.config/wandb/settings
2025-05-06 23:15:18,167 INFO    MainThread:3005 [wandb_setup.py:_flush():68] Loading settings from /home/joaopaulo/Projects/internvl3-siamese/notebooks/wandb/settings
2025-05-06 23:15:18,167 INFO    MainThread:3005 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-05-06 23:15:18,168 INFO    MainThread:3005 [wandb_init.py:_log_setup():528] Logging user logs to /home/joaopaulo/Projects/internvl3-siamese/notebooks/wandb/run-20250506_231518-d44vwmxe/logs/debug.log
2025-05-06 23:15:18,168 INFO    MainThread:3005 [wandb_init.py:_log_setup():529] Logging internal logs to /home/joaopaulo/Projects/internvl3-siamese/notebooks/wandb/run-20250506_231518-d44vwmxe/logs/debug-internal.log
2025-05-06 23:15:18,168 INFO    MainThread:3005 [wandb_init.py:init():639] calling init triggers
2025-05-06 23:15:18,168 INFO    MainThread:3005 [wandb_init.py:init():645] wandb.init called with sweep_config: {}
config: {}
2025-05-06 23:15:18,168 INFO    MainThread:3005 [wandb_init.py:init():683] wandb.init() called when a run is still active
2025-05-06 23:15:18,169 ERROR   MainThread:3005 [wandb_init.py:init():1315] error in wandb.init()
Traceback (most recent call last):
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1305, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 684, in init
    with telemetry.context() as tel:
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 791, in _telemetry_callback
    self._telemetry_flush()
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 804, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 222, in send_record_publish
    self.send_server_request(server_req)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-06 23:15:18,542 INFO    MainThread:3005 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2025-05-06 23:15:18,542 INFO    MainThread:3005 [wandb_init.py:_pause_backend():439] pausing backend
2025-05-06 23:15:34,632 INFO    MainThread:3005 [wandb_init.py:_resume_backend():444] resuming backend
2025-05-06 23:15:34,733 ERROR   MainThread:3005 [wandb_init.py:init():1315] error in wandb.init()
Traceback (most recent call last):
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1297, in init
    wi.setup(
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 230, in setup
    with telemetry.context(obj=self._init_telemetry_obj) as tel:
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 791, in _telemetry_callback
    self._telemetry_flush()
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 804, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 222, in send_record_publish
    self.send_server_request(server_req)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-06 23:15:34,929 INFO    MainThread:3005 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2025-05-06 23:15:34,930 INFO    MainThread:3005 [wandb_init.py:_pause_backend():439] pausing backend
